working_dir = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/tempdir"
worker_threads = 8
server_address = "0.0.0.0"
server_port = "8080"
buffer_size = 20480
[server]
domain_name = "signatrust.test.osinfra.cn"
tls_cert = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/client/server.crt"
tls_key = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/client/server.key"
type = "single"
server_address = "0.0.0.0"
server_port = "8080"
# type dns used for client round robin when multiple ip addresses are bound to single domain
#type = "dns"
#server_name = "a.svc.cluster"
#server_port = "8080"
