name = "application"
tls_cert = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/server/server.crt"
tls_key = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/server/server.key"
ca_root = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/server/ca_root.pem"
[data-server]
server_ip = "0.0.0.0"
server_port = "8080"
[control-server]
server_ip = "0.0.0.0"
server_port = "8088"
cookie_key = "2B5AEC57F7CC4FF8B4120AA7E4527C7B597CAF43183E453A9B981991E6FACB76"
[oidc]
client_id = ""
client_secret = ""
auth_url = "http://119.8.46.32:9999/oneid/oidc/authorize"
token_url = "http://119.8.46.32:9999/oneid/oidc/token"
userinfo_url = "http://119.8.46.32:9999/oneid/oidc/user"
redirect_url = "https://signatrust.test.osinfra.cn/api/v1/users/callback"
[kms-provider]
type = "dummy"
kms_id = "65ccb4d8-cc45-4139-b380-2fcff184ac4f"
endpoint = "cn-north-4.myhuaweicloud.com"
project_name = "cn-north-4"
project_id = "25f40abeecb84d3e90731de258ca71ec"
username = "freesky-edward"
password = ""
domain="freesky-edward"
[database]
connection_url = "mysql://test:test@127.0.0.1:3306/signatrust"
max_connection = 5
[encryption-engine]
keep_in_days = 180
algorithm = "aes256gsm"
