name = "application"
server_tls_cert = ""
server_tls_key = ""
[data-server]
server_ip = "0.0.0.0"
server_port = "8080"
[kms-provider]
type = "huaweicloud"
kms_id = "65ccb4d8-cc45-4139-b380-2fcff184ac4f"
endpoint = "cn-north-4.myhuaweicloud.com"
project_name = "cn-north-4"
project_id = "25f40abeecb84d3e90731de258ca71ec"
username = "freesky-edward"
password = "ddhjx@1234!@#$"
domain="freesky-edward"
[database]
connection_url = "mysql://test:test@127.0.0.1:3306/signatrust"
max_connection = 5
